version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8125:5000"  # Map host port 8123 to container port 5000
    environment:
      - DATABASE_URL=sqlite:////data/app.db  # SQLite database URL
    volumes:
      - db_data:/data  # Volume to persist SQLite database
    networks:
      - task

networks:
  task:
    driver: bridge

volumes:
  db_data:
